apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: springapp
  labels:
    app: springapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: sparingapp
    spec:
      # nodeSelector:
      #   eks.amazonaws.com/nodegroup: GS-Nodegroup
      # tolerations:
      # - key: "eks.amazonaws.com/nodegroup"
      #   value: "GS-Nodegroup"
      #   effect: "NoSchedule"
      # serviceAccountName: crypto-sa
      containers:
      - name: springapp
        image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: 8080